name: app_creaty
description: App Creaty - Drag n Drop Mobile Developement Tool

publish_to: "none"

version: 0.11.3

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  after_layout: ^1.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dart_date: ^1.2.1
  dartx: ^1.1.0
  device_frame:
    git: https://github.com/dungngminh/adjusted_device_frame.git
  equatable: ^2.0.5
  file_selector: ^1.0.1
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter

  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_colorpicker: ^1.0.3
  flutter_fancy_tree_view: ^1.1.1
  flutter_json_viewer: ^1.0.1
  flutter_lazy_indexed_stack: ^0.0.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.5
  freezed: ^2.4.2
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_widget:
    git:
      url: https://github.com/dungngminh/adjusted_json_widget.git
      ref: main
  layout: ^1.0.3
  logger: ^1.3.0
  multi_split_view: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.2
  recase: ^4.1.0
  replay_bloc: ^0.2.3
  shortid: ^0.1.2
  uuid: ^3.0.7
  window_manager: ^0.3.2
  yaml: ^3.1.1
  rxdart_ext: ^0.2.9
  native_context_menu: ^0.2.2+5
  supabase_flutter: ^1.10.14
  flutter_secure_storage: ^8.0.0
  string_validator: ^1.0.0
  dart_code_viewer2: ^1.0.1
  sentry_flutter: ^7.8.0
  context_menus: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/outline/
    - assets/icons/bold/
    - assets/icons/other/
    - assets/icons/components/
    - assets/images/
    - assets/fonts/
    - assets/images/svg/
    - assets/images/png/
  #   - assets/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/commons/gen/

  integrations:
    flutter_svg: true

scripts:
  asset:
    - fluttergen

  get:
    - flutter pub get

  runner:
    - flutter pub run build_runner build --delete-conflicting-outputs

  rebuild:
    - flutter clean
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs

  rebuild_mac:
    - flutter clean
    - flutter pub get
    - cd macos/
    - pod install
    - cd ..
    - flutter pub run build_runner build --delete-conflicting-outputs
