name: app_creaty
description: An app can create app

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dart_date: ^1.2.1
  dartx: ^1.1.0
  device_frame: ^1.1.0
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter

  flutter_lazy_indexed_stack: ^0.0.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  gap: ^2.0.1
  go_router: ^6.5.3
  intl: ^0.17.0
  logger: ^1.3.0
  multi_split_view: ^2.4.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.13
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/outline/
    - assets/icons/bold/
    - assets/icons/other/
    - assets/images/
    - assets/fonts/
    - assets/images/svg/
    # - assets/images/png/
  #   - assets/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/commons/gen/

  integrations:
    flutter_svg: true
