include: package:very_good_analysis/analysis_options.4.0.0.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
    require_trailing_commas: true
    prefer_single_quotes: true
    cascade_invocations: true
    always_use_package_imports: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_string_interpolations: true
    omit_local_variable_types: true
    always_put_required_named_parameters_first: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
