name: json_widget
description: A json widget package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.11

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  url_launcher: ^6.1.10
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
