name: CICD AppCreaty

on:
  push:
    branches:
      - master

env:
  FLUTTER_VERSION: "3.10.6"

jobs:
  build_on_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Install os dependencies
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libsecret-1-dev liblzma-dev libjsoncpp-dev libstdc++-12-dev libunwind-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Create env.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env.json"
          json: '{"SUPABASE_URL":"${{secrets.SUPABASE_URL}}", "SUPABASE_ANON":"${{secrets.SUPABASE_ANON}}"}'
      - name: Get version
        id: version
        uses: NiklasLehnfeld/flutter-version-number-action@main
      - name: Build artifacts
        run: flutter build linux --release --dart-define-from-file=env.json
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: app_creaty-${{ steps.version.outputs.version-number }}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Release to github
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.version.outputs.version-number }}
          tag_name: ${{ steps.version.outputs.version-number }}
          generate_release_notes: true
          files: build/linux/x64/release/bundle/app_creaty-${{ steps.version.outputs.version-number }}-linux.zip

  build_on_windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Create env.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env.json"
          json: '{"SUPABASE_URL":"${{secrets.SUPABASE_URL}}", "SUPABASE_ANON":"${{secrets.SUPABASE_ANON}}"}'
      - name: Get version
        id: version
        uses: NiklasLehnfeld/flutter-version-number-action@main
      - name: Build artifacts
        run: flutter build windows --release --dart-define-from-file=env.json
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: app_creaty-${{ steps.version.outputs.version-number }}-windows.zip
          directory: build/windows/runner/Release
      - name: Release to github
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.version.outputs.version-number }}
          tag_name: ${{ steps.version.outputs.version-number }}
          generate_release_notes: true
          files: build/windows/runner/Release/app_creaty-${{ steps.version.outputs.version-number }}-windows.zip

  build_on_macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Create env.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env.json"
          json: '{"SUPABASE_URL":"${{secrets.SUPABASE_URL}}", "SUPABASE_ANON":"${{secrets.SUPABASE_ANON}}"}'
      - name: Get version
        id: version
        uses: NiklasLehnfeld/flutter-version-number-action@main
      - name: Build artifacts
        run: flutter build macos --release --no-tree-shake-icons --dart-define-from-file=env.json
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: app_creaty-${{steps.version.outputs.version-number}}-macos.zip
          directory: build/macos/Build/Products/Release
      - name: Release to github
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.version.outputs.version-number }}
          tag_name: ${{ steps.version.outputs.version-number }}
          generate_release_notes: true
          files: build/macos/Build/Products/Release/app_creaty-${{steps.version.outputs.version-number}}-macos.zip
