name: Initialize 

on:
  push:
    branches:
      - master

env:
  FLUTTER_VERSION: "3.16.x"

jobs:
  init_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Create env.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env.json"
          json: '{"SUPABASE_URL":"${{secrets.SUPABASE_URL}}", "SUPABASE_ANON":"${{secrets.SUPABASE_ANON}}"}'
      - name: Enable desktop platform
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-web
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs